---
title: "R Notebook"
output: html_notebook
---
## Libraries

```{r, echo = FALSE}
library(tidyverse)
library(reticulate)
library(markovchain)
library(diagram)
library(gridExtra)
library(grid)
library(data.table)
set.seed(12345)

load("final_output.Rdata")

```

```{r}

plot.objective <- grid.arrange(solnplot_ep , solnplot_dml, ncol = 2)

plot.profit <- grid.arrange(profitplot_ep , profitplot_dml, ncol = 2)

plot.cy <- grid.arrange(cyplot_ep , cyplot_dml, ncol = 2)

plot.waterinvest <- grid.arrange(waterinvestplot_ep , waterinvestplot_dml, ncol = 2)

plot.elcinvest <- grid.arrange(elcinvestplot_ep , elcinvestplot_dml, ncol = 2)

plot.waterop <- grid.arrange(waterop_ep , waterop_dml, ncol = 2)

plot.elcop <- grid.arrange(elcop_ep , elcop_dml, ncol = 2)


```
```{r}
plot.objective
plot.profit
plot.cy
plot.waterinvest
plot.elcinvest
plot.waterop
plot.elcop
```


```{r}
sim_stats_trad <- rbind(sim_stats_trad_ep,sim_stats_trad_dml) %>% mutate(Climate_Probability = c(rep('Equally Probable',4),rep('Dry Most Likely',4))) %>% relocate(Climate_Probability)

value_of_solns <- rbind(value_of_solns_ep,value_of_solns_DML) %>% mutate(Climate_Probability = c('Equally Probable', 'Dry Most Likely'))

sim_stats_trad

value_of_solns
```
```{r}
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/objectives.pdf", plot.objective)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/profit.pdf", plot.profit)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/crop_yield.pdf", plot.cy)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/waterinvest.pdf", plot.waterinvest)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/elcinvest.pdf", plot.elcinvest)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/waterop.pdf", plot.waterop)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/elcop.pdf", plot.elcop)

write.csv(sim_stats_trad, "~/Coding/R/Research/Farm Model/csvs/simstatstrad.csv")
write.csv(value_of_solns, "~/Coding/R/Research/Farm Model/csvs/solnvalues.csv")
```

