---
title: "R Notebook"
output: html_notebook
---
## Libraries

```{r, echo = FALSE}
library(tidyverse)
library(reticulate)
library(markovchain)
library(diagram)
library(gridExtra)
library(grid)
set.seed(12345)

load("MI-EP.Rdata")

```

## Graphs

### Profit

```{r}

profitdetplot <- scenario_yearly_avg %>% 
  ggplot() + 
  geom_bar(aes(x = sim, y = profit_MM, fill = sim), stat = 'identity') +
  geom_text(aes(x = sim, y = profit_MM, label=round(profit_MM,2)), vjust = -1, size=5)+
  geom_point(aes(y = precip_cm/25, x = sim), size = 2, shape = 15) +
  scale_y_continuous(sec.axis = sec_axis(~.*25, name = 'Precipitation (cm)'), limits = c(0,4))+
  theme_minimal()+
  theme(plot.title = element_text(size = 14, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        axis.text.y.right = element_blank(),
        axis.title.y.right = element_blank(),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'MI-EP Deterministic Scenarios', y = 'Profit ($ MM)', x = '', size = 8)+
  scale_fill_brewer(palette = "Dark2")+
  guides(fill = FALSE)


profitrealplot <- scenario_realized_yearly_avg %>% 
  ggplot() + 
  geom_bar(aes(x = sim, y = profit_MM, fill = sim), stat = 'identity') +
  geom_text(aes(x = sim, y = profit_MM, label=round(profit_MM,2)), vjust = -1.5, size=5)+
  geom_point(aes(y = precip_cm/25, x = sim), size = 2, shape = 15) +
  scale_y_continuous(sec.axis = sec_axis(~.*25, name = 'Precipitation (cm)'), limits = c(0,4))+
  theme_minimal()+
  theme(plot.title = element_text(size = 14, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        axis.text.y.left = element_blank(),
        axis.title.y.left = element_blank(),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'MI-EP Realized Scenarios', y = 'Profit ($ MM)', x = '', size = 8)+
  scale_fill_brewer(palette = "Dark2")+
  guides(fill = FALSE)





profitplot <- grid.arrange(profitdetplot, profitrealplot, ncol = 2)

profitplot
```
### Crop Yield

```{r}

cydetplot <- scenario_yearly_avg %>% 
  ggplot() + 
  geom_bar(aes(x = sim, y = crop_yield_tonne, fill = sim), stat = 'identity') +
  geom_text(aes(x = sim, y = crop_yield_tonne, label=round(crop_yield_tonne,0)), vjust = -1, size=5)+
  geom_point(aes(y = water_cm*8, x = sim), size = 2, shape = 17) +
  scale_y_continuous(sec.axis = sec_axis(~./8, name = 'Water Depth (cm)'), limits = c(0,800))+
  theme_minimal()+
  theme(plot.title = element_text(size = 14, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        axis.text.y.right = element_blank(),
        axis.title.y.right = element_blank(),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'MI-EP Deterministic Scenarios', y = 'Crop Yield (tonnes)', x = '', size = 8)+
  scale_fill_brewer(palette = "Dark2")+
  guides(fill = FALSE)


cyrealplot <- scenario_realized_yearly_avg %>% 
  ggplot() + 
  geom_bar(aes(x = sim, y = crop_yield_tonne, fill = sim), stat = 'identity') +
  geom_text(aes(x = sim, y = crop_yield_tonne, label=round(crop_yield_tonne,0)), vjust = -1, size=5)+
  geom_point(aes(y = water_cm*8, x = sim), size = 2, shape = 17) +
  scale_y_continuous(sec.axis = sec_axis(~./8, name = 'Water Depth (cm)'), limits = c(0,800))+
  theme_minimal()+
  theme(plot.title = element_text(size = 14, face = 'bold'),  
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        axis.text.y.left = element_blank(),
        axis.title.y.left = element_blank(),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'MI-EP Realized Scenarios', y = 'Crop Yield (tonnes)', x = '', size = 8)+
  scale_fill_brewer(palette = "Dark2")+
  guides(fill = FALSE)

cyplot <- grid.arrange(cydetplot, cyrealplot, ncol = 2)

cyplot

```

#### Investments

```{r}
waterinvestplot <- scenario_yearly_avg %>% 
  ggplot() + 
  geom_bar(aes(x = sim, y = alt_water_cap_cm, fill = sim), stat = 'identity') +
  geom_text(aes(x = sim, y = alt_water_cap_cm, label=round(alt_water_cap_cm,1)), vjust = -1, size=5)+
  geom_point(aes(y = water_cm/2.5, x = sim), size = 2, shape = 17) +
  scale_y_continuous(sec.axis = sec_axis(~.*2.5, name = 'Water Depth (cm)'), limits = c(0,40))+
  theme_minimal()+
  theme(plot.title = element_text(size = 14, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'MI-EP Water Investments', y = 'Water Capacity (cm)', x = '', size = 8)+
  scale_fill_brewer(palette = "Dark2")+
  guides(fill = FALSE)

elcinvestplot <- scenario_yearly_avg %>% 
    ggplot() + 
  geom_bar(aes(x = sim, y = alt_elc_cap_kW, fill = sim), stat = 'identity') +
  geom_text(aes(x = sim, y = alt_elc_cap_kW, label=round(alt_elc_cap_kW,0)), vjust = -1, size=5)+
  geom_point(aes(y = elc_prod_MWh/2, x = sim), size = 2, shape = 17) +
  scale_y_continuous(sec.axis = sec_axis(~.*2, name = 'Electricity Produced (MWh)'), limits = c(0,600))+
  theme_minimal()+
  theme(plot.title = element_text(size = 14, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'MI-EP Electricity Investments', y = 'Electricity Capacity (kW)', x = '', size = 8)+
  scale_fill_brewer(palette = "Dark2")+
  guides(fill = FALSE)


investplot <- grid.arrange(waterinvestplot, elcinvestplot, ncol = 2)

```



```{r}


stochvclimate1_df %>%  
  pivot_longer(c(alt_water,irrigation_water,total_water,precip), names_to = 'Water_Source', values_to = 'Water_Depth') %>%
  filter(Water_Source != 'total_water') %>%
  filter(scenario == 'Stochastic_Model') %>%
  ggplot(aes(x = Year, y = Water_Depth, group = Water_Source, fill = Water_Source, color = Water_Source))+
  geom_area(position = position_stack(reverse = TRUE))+
  scale_y_continuous(breaks = seq(from = 0, to = 125, by = 50), limits =c(0,125))+
  scale_x_continuous(breaks = seq(from = 1, to = 25, by = 2))+
  theme_minimal()+
  theme(plot.title = element_text(size = 16, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'MI-EP Stochastic Scenario', y = 'Water Depth (cm)', x = 'Year', size = 8) -> stoch_water

stochvclimate1_df %>%  
  pivot_longer(c(alt_water,irrigation_water,total_water,precip), names_to = 'Water_Source', values_to = 'Water_Depth') %>%
  filter(Water_Source != 'total_water') %>%
  filter(scenario == 'Dry_Climate') %>%
  ggplot(aes(x = Year, y = Water_Depth, group = Water_Source, fill = Water_Source, color = Water_Source))+
  geom_area(position = position_stack(reverse = TRUE))+
  scale_y_continuous(breaks = seq(from = 0, to = 125, by = 50), limits =c(0,125))+
  scale_x_continuous(breaks = seq(from = 1, to = 25, by = 2))+
  theme_minimal()+
  theme(plot.title = element_text(size = 16, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'Dry Climate Deterministic', y = 'Water Depth (cm)', x = 'Year', size = 8) -> plot_c1_climate_water

stochvclimate1_df %>%  
  pivot_longer(c(alt_water,irrigation_water,total_water,precip), names_to = 'Water_Source', values_to = 'Water_Depth') %>%
  filter(Water_Source != 'total_water') %>%
  filter(scenario == 'Dry_Climate_Realized') %>%
  ggplot(aes(x = Year, y = Water_Depth, group = Water_Source, fill = Water_Source, color = Water_Source))+
  geom_area(position = position_stack(reverse = TRUE))+
  scale_y_continuous(breaks = seq(from = 0, to = 125, by = 50), limits =c(0,125))+
  scale_x_continuous(breaks = seq(from = 1, to = 25, by = 2))+
  theme_minimal()+
  theme(plot.title = element_text(size = 16, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'Dry Climate Realized', y = 'Water Depth (cm)', x = 'Year', size = 8) -> plot_c1_climate_realized_water

stochvclimate1_df %>%  
  pivot_longer(c(alt_elc,utility_elc,total_elc), names_to = 'ELC_Source', values_to = 'ELC_Depth') %>%
  filter(ELC_Source != 'total_elc') %>%
  filter(scenario == 'Stochastic_Model') %>%
  ggplot(aes(x = Year, y = ELC_Depth/1000, group = ELC_Source, fill = ELC_Source, color = ELC_Source))+
  geom_area(position = position_stack(reverse = TRUE))+
  scale_y_continuous(breaks = seq(from = 0, to = 1250, by = 250), limits =c(0,1250))+
  scale_x_continuous(breaks = seq(from = 1, to = 25, by = 2))+
  theme_minimal()+
  theme(plot.title = element_text(size = 16, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'MI-EP Stochastic Scenario', y = 'Electricity Produced (MWh)', x = 'Year', size = 8) -> stoch_elc

stochvclimate1_df %>%  
  pivot_longer(c(alt_elc,utility_elc,total_elc), names_to = 'ELC_Source', values_to = 'ELC_Depth') %>%
  filter(ELC_Source != 'total_elc') %>%
  filter(scenario == 'Dry_Climate') %>%
  ggplot(aes(x = Year, y = ELC_Depth/1000, group = ELC_Source, fill = ELC_Source, color = ELC_Source))+
  geom_area(position = position_stack(reverse = TRUE))+
  scale_y_continuous(breaks = seq(from = 0, to = 1250, by = 250), limits =c(0,1250))+
  scale_x_continuous(breaks = seq(from = 1, to = 25, by = 2))+
  theme_minimal()+
  theme(plot.title = element_text(size = 14, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'Dry Climate Deterministic', y = 'Electricity Produced (MWh)', x = 'Year', size = 8) -> plot_c1_climate_elc

stochvclimate1_df %>%  
  pivot_longer(c(alt_elc,utility_elc,total_elc), names_to = 'ELC_Source', values_to = 'ELC_Depth') %>%
  filter(ELC_Source != 'total_elc') %>%
  filter(scenario == 'Dry_Climate_Realized') %>%
  ggplot(aes(x = Year, y = ELC_Depth/1000, group = ELC_Source, fill = ELC_Source, color = ELC_Source))+
  geom_area(position = position_stack(reverse = TRUE))+
  scale_y_continuous(breaks = seq(from = 0, to = 1250, by = 250), limits =c(0,1250))+
  scale_x_continuous(breaks = seq(from = 1, to = 25, by = 2))+
  theme_minimal()+
 theme(plot.title = element_text(size = 14, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'Dry Climate Realized', y = 'Electricity Produced (MWh)', x = 'Year', size = 8) -> plot_c1_climate_realized_elc



wateropc1 <- grid.arrange(plot_c1_climate_water, plot_c1_climate_realized_water, ncol = 2)
elcopc1 <- grid.arrange(plot_c1_climate_elc, plot_c1_climate_realized_elc, ncol = 2)

stoch_water
stoch_elc
wateropc1
elcopc1
```
```{r}


stochvclimate2_df %>%  
  pivot_longer(c(alt_water,irrigation_water,total_water,precip), names_to = 'Water_Source', values_to = 'Water_Depth') %>%
  filter(Water_Source != 'total_water') %>%
  filter(scenario == 'Dry_Moderate_Climate') %>%
  ggplot(aes(x = Year, y = Water_Depth, group = Water_Source, fill = Water_Source, color = Water_Source))+
  geom_area(position = position_stack(reverse = TRUE))+
  scale_y_continuous(breaks = seq(from = 0, to = 125, by = 50), limits =c(0,125))+
  scale_x_continuous(breaks = seq(from = 1, to = 25, by = 2))+
  theme_minimal()+
 theme(plot.title = element_text(size = 14, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'Dry-Moderate Climate Deterministic', y = 'Water Depth (cm)', x = 'Year', size = 8) -> plot_c2_climate_water

stochvclimate2_df %>%  
  pivot_longer(c(alt_water,irrigation_water,total_water,precip), names_to = 'Water_Source', values_to = 'Water_Depth') %>%
  filter(Water_Source != 'total_water') %>%
  filter(scenario == 'Dry_Moderate_Climate_Realized') %>%
  ggplot(aes(x = Year, y = Water_Depth, group = Water_Source, fill = Water_Source, color = Water_Source))+
  geom_area(position = position_stack(reverse = TRUE))+
  scale_y_continuous(breaks = seq(from = 0, to = 125, by = 50), limits =c(0,125))+
  scale_x_continuous(breaks = seq(from = 1, to = 25, by = 2))+
  theme_minimal()+
 theme(plot.title = element_text(size = 14, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'Dry-Moderate Climate Realized', y = 'Water Depth (cm)', x = 'Year', size = 8) -> plot_c2_climate_realized_water


stochvclimate2_df %>%  
  pivot_longer(c(alt_elc,utility_elc,total_elc), names_to = 'ELC_Source', values_to = 'ELC_Depth') %>%
  filter(ELC_Source != 'total_elc') %>%
  filter(scenario == 'Dry_Moderate_Climate') %>%
  ggplot(aes(x = Year, y = ELC_Depth/1000, group = ELC_Source, fill = ELC_Source, color = ELC_Source))+
  geom_area(position = position_stack(reverse = TRUE))+
  scale_y_continuous(breaks = seq(from = 0, to = 1250, by = 250), limits =c(0,1250))+
  scale_x_continuous(breaks = seq(from = 1, to = 25, by = 2))+
  theme_minimal()+
 theme(plot.title = element_text(size = 14, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'Dry-Moderate Climate Deterministic', y = 'Electricity Produced (MWh)', x = 'Year', size = 8) -> plot_c2_climate_elc

stochvclimate2_df %>%  
  pivot_longer(c(alt_elc,utility_elc,total_elc), names_to = 'ELC_Source', values_to = 'ELC_Depth') %>%
  filter(ELC_Source != 'total_elc') %>%
  filter(scenario == 'Dry_Moderate_Climate_Realized') %>%
  ggplot(aes(x = Year, y = ELC_Depth/1000, group = ELC_Source, fill = ELC_Source, color = ELC_Source))+
  geom_area(position = position_stack(reverse = TRUE))+
  scale_y_continuous(breaks = seq(from = 0, to = 1250, by = 250), limits =c(0,1250))+
  scale_x_continuous(breaks = seq(from = 1, to = 25, by = 2))+
  theme_minimal()+
theme(plot.title = element_text(size = 14, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'Dry-Moderate Climate Realized', y = 'Electricity Produced (MWh)', x = 'Year', size = 8) -> plot_c2_climate_realized_elc



wateropc2 <- grid.arrange(plot_c2_climate_water, plot_c2_climate_realized_water, ncol = 2)
elcopc2 <- grid.arrange(plot_c2_climate_elc, plot_c2_climate_realized_elc, ncol = 2)

wateropc2
elcopc2
```
```{r}

stochvclimate3_df %>%  
  pivot_longer(c(alt_water,irrigation_water,total_water,precip), names_to = 'Water_Source', values_to = 'Water_Depth') %>%
  filter(Water_Source != 'total_water') %>%
  filter(scenario == 'Moderate_Climate') %>%
  ggplot(aes(x = Year, y = Water_Depth, group = Water_Source, fill = Water_Source, color = Water_Source))+
  geom_area(position = position_stack(reverse = TRUE))+
  scale_y_continuous(breaks = seq(from = 0, to = 125, by = 50), limits =c(0,125))+
  scale_x_continuous(breaks = seq(from = 1, to = 25, by = 2))+
  theme_minimal()+
  theme(plot.title = element_text(size = 16, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'Moderate Climate Deterministic', y = 'Water Depth (cm)', x = 'Year', size = 8) -> plot_c3_climate_water

stochvclimate3_df %>%  
  pivot_longer(c(alt_water,irrigation_water,total_water,precip), names_to = 'Water_Source', values_to = 'Water_Depth') %>%
  filter(Water_Source != 'total_water') %>%
  filter(scenario == 'Moderate_Climate_Realized') %>%
  ggplot(aes(x = Year, y = Water_Depth, group = Water_Source, fill = Water_Source, color = Water_Source))+
  geom_area(position = position_stack(reverse = TRUE))+
  scale_y_continuous(breaks = seq(from = 0, to = 125, by = 50), limits =c(0,125))+
  scale_x_continuous(breaks = seq(from = 1, to = 25, by = 2))+
  theme_minimal()+
  theme(plot.title = element_text(size = 16, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'Moderate Climate Realized', y = 'Water Depth (cm)', x = 'Year', size = 8) -> plot_c3_climate_realized_water


stochvclimate3_df %>%  
  pivot_longer(c(alt_elc,utility_elc,total_elc), names_to = 'ELC_Source', values_to = 'ELC_Depth') %>%
  filter(ELC_Source != 'total_elc') %>%
  filter(scenario == 'Moderate_Climate') %>%
  ggplot(aes(x = Year, y = ELC_Depth/1000, group = ELC_Source, fill = ELC_Source, color = ELC_Source))+
  geom_area(position = position_stack(reverse = TRUE))+
  scale_y_continuous(breaks = seq(from = 0, to = 1250, by = 250), limits =c(0,1250))+
  scale_x_continuous(breaks = seq(from = 1, to = 25, by = 2))+
  theme_minimal()+
  theme(plot.title = element_text(size = 16, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'Moderate Climate Deterministic', y = 'Electricity Produced (MWh)', x = 'Year', size = 8) -> plot_c3_climate_elc

stochvclimate3_df %>%  
  pivot_longer(c(alt_elc,utility_elc,total_elc), names_to = 'ELC_Source', values_to = 'ELC_Depth') %>%
  filter(ELC_Source != 'total_elc') %>%
  filter(scenario == 'Moderate_Climate_Realized') %>%
  ggplot(aes(x = Year, y = ELC_Depth/1000, group = ELC_Source, fill = ELC_Source, color = ELC_Source))+
  geom_area(position = position_stack(reverse = TRUE))+
  scale_y_continuous(breaks = seq(from = 0, to = 1250, by = 250), limits =c(0,1250))+
  scale_x_continuous(breaks = seq(from = 1, to = 25, by = 2))+
  theme_minimal()+
  theme(plot.title = element_text(size = 16, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'Moderate Climate Realized', y = 'Electricity Produced (MWh)', x = 'Year', size = 8) -> plot_c3_climate_realized_elc



wateropc3 <- grid.arrange(plot_c3_climate_water, plot_c3_climate_realized_water, ncol = 2)
elcopc3 <- grid.arrange(plot_c3_climate_elc, plot_c3_climate_realized_elc, ncol = 2)

wateropc3
elcopc3
```



```{r}

stochvclimate4_df %>%  
  pivot_longer(c(alt_water,irrigation_water,total_water,precip), names_to = 'Water_Source', values_to = 'Water_Depth') %>%
  filter(Water_Source != 'total_water') %>%
  filter(scenario == 'Wet_Climate') %>%
  ggplot(aes(x = Year, y = Water_Depth, group = Water_Source, fill = Water_Source, color = Water_Source))+
  geom_area(position = position_stack(reverse = TRUE))+
  scale_y_continuous(breaks = seq(from = 0, to = 125, by = 50), limits =c(0,125))+
  scale_x_continuous(breaks = seq(from = 1, to = 25, by = 2))+
  theme_minimal()+
   theme(plot.title = element_text(size = 16, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'Wet Climate Deterministic', y = 'Water Depth (cm)', x = 'Year', size = 8) -> plot_c4_climate_water

stochvclimate4_df %>%  
  pivot_longer(c(alt_water,irrigation_water,total_water,precip), names_to = 'Water_Source', values_to = 'Water_Depth') %>%
  filter(Water_Source != 'total_water') %>%
  filter(scenario == 'Wet_Climate_Realized') %>%
  ggplot(aes(x = Year, y = Water_Depth, group = Water_Source, fill = Water_Source, color = Water_Source))+
  geom_area(position = position_stack(reverse = TRUE))+
  scale_y_continuous(breaks = seq(from = 0, to = 125, by = 50), limits =c(0,125))+
  scale_x_continuous(breaks = seq(from = 1, to = 25, by = 2))+
  theme_minimal()+
  theme(plot.title = element_text(size = 16, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'Wet Climate Realized', y = 'Water Depth (cm)', x = 'Year', size = 8) -> plot_c4_climate_realized_water


stochvclimate4_df %>%  
  pivot_longer(c(alt_elc,utility_elc,total_elc), names_to = 'ELC_Source', values_to = 'ELC_Depth') %>%
  filter(ELC_Source != 'total_elc') %>%
  filter(scenario == 'Wet_Climate') %>%
  ggplot(aes(x = Year, y = ELC_Depth/1000, group = ELC_Source, fill = ELC_Source, color = ELC_Source))+
  geom_area(position = position_stack(reverse = TRUE))+
  scale_y_continuous(breaks = seq(from = 0, to = 1250, by = 250), limits =c(0,1250))+
  scale_x_continuous(breaks = seq(from = 1, to = 25, by = 2))+
  theme_minimal()+
  theme(plot.title = element_text(size = 16, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'Wet Climate Deterministic', y = 'Electricity Produced (MWh)', x = 'Year', size = 8) -> plot_c4_climate_elc

stochvclimate4_df %>%  
  pivot_longer(c(alt_elc,utility_elc,total_elc), names_to = 'ELC_Source', values_to = 'ELC_Depth') %>%
  filter(ELC_Source != 'total_elc') %>%
  filter(scenario == 'Wet_Climate_Realized') %>%
  ggplot(aes(x = Year, y = ELC_Depth/1000, group = ELC_Source, fill = ELC_Source, color = ELC_Source))+
  geom_area(position = position_stack(reverse = TRUE))+
  scale_y_continuous(breaks = seq(from = 0, to = 1250, by = 250), limits =c(0,1250))+
  scale_x_continuous(breaks = seq(from = 1, to = 25, by = 2))+
  theme_minimal()+
  theme(plot.title = element_text(size = 16, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'Wet Climate Realized', y = 'Electricity Produced (MWh)', x = 'Year', size = 8) -> plot_c4_climate_realized_elc



wateropc4 <- grid.arrange(plot_c4_climate_water, plot_c4_climate_realized_water, ncol = 2)
elcopc4 <- grid.arrange(plot_c4_climate_elc, plot_c4_climate_realized_elc, ncol = 2)

wateropc4
elcopc4
```


```{r}
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/MI-EP_profit.pdf", profitplot)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/MI-EP_cy.pdf", cyplot)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/MI-EP_invest.pdf", investplot)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/MI-EP-SS_water.pdf", stoch_water)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/MI-EP-SS_elc.pdf", stoch_elc)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/MI-EP-DC-DS_water.pdf", wateropc1)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/MI-EP-DC-DS_elc.pdf", elcopc1)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/MI-EP-DMC-DS_water.pdf", wateropc2)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/MI-EP-DMC-DS_elc.pdf", elcopc2)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/MI-EP-MC-DS_water.pdf", wateropc3)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/MI-EP-MC-DS_elc.pdf", elcopc3)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/MI-EP-WC-DS_water.pdf", wateropc4)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/MI-EP-WC-DS_elc.pdf", elcopc4)
```