---
title: "R Notebook"
output: html_notebook
---
## Libraries

```{r, echo = FALSE}
library(tidyverse)
library(reticulate)
library(markovchain)
library(diagram)
library(gridExtra)
library(grid)
library(data.table)
set.seed(12345)

load("MI-DML.Rdata")

```

## Graphs



## Value of Solution Graphs

```{r}
scenario_yearly_avg_trad

scenario_yearly_avg_trad[4,]
```
```{r}
scenario_yearly_avg_trad %>% 
  ggplot(aes(x = sim, y = profit_MM, fill = sim)) + 
  geom_bar(aes(x = sim, y = profit_MM, fill = sim), stat = 'identity', position = position_dodge2(preserve = "single")) +
  geom_text(aes(x = sim, y = profit_MM, label=round(profit_MM,3)), vjust = -2, size=5, position = position_dodge(width = 1))+
  scale_y_continuous(limits = c(0,3))+
  scale_x_discrete(labels=c("Perfect \n Information", "Known Climate \n Unknown \n Weather", "Stochastic", "Expected \n Value"))+
  theme_minimal()+
  theme(plot.title = element_text(size = 14, face = 'bold'), 
        legend.position = 'none', 
        legend.text = element_text(size = 12), 
        legend.title = element_text(size = 12), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust =0.5),
        #axis.text.y.right = element_blank(),
        #axis.title.y.right = element_blank(),
        #legend.key.width = unit(0.12, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  scale_fill_manual(values = c("Perfect Information" = "red", "Known Climate, Unknown Weather" = "green4", 'Stochastic' = 'blue', "Expected Value" = "purple"))+
  labs(title = 'DML: Objective Values', y = 'Profit ($ MM)', x = '', size = 8, fill = 'Weather')+
  guides(fill = guide_legend(override.aes = list(shape = NA))) -> solnplot


solnplot
```


### Profit

```{r}

scenario_yearly_avg

scenario_yearly_avg_trad[4,]


scenario_avg <- scenario_yearly_avg %>%  rbind(scenario_yearly_avg_trad[4,]) %>% mutate(sim = c('Stochastic_avg', rep(c('Known Climate Unknown Weather', 'Stochastic'),4), 'Expected Value' ) ) %>%
  mutate(Climate = c('Stoch', 'DC', 'DC', 'DMC', 'DMC', 'MC', 'MC', 'WC', 'WC', 'EV')) 


scenario_avg$sim <- ordered(scenario_avg$sim, levels = c('Known Climate Unknown Weather', 'Stochastic', 'Stochastic_avg', 'Expected Value'  ))

scenario_avg$Climate <- ordered(scenario_avg$Climate, levels = c('DC', 'DMC', 'MC', 'WC', 'Stoch', 'EV'))

scenario_avg
```


```{r}
scenario_avg %>% filter(sim != 'Stochastic_avg') %>% filter(sim != 'Expected Value') %>%
  ggplot(aes(x = sim, y = profit_MM, fill = Climate)) + 
  geom_bar(aes(x = sim, y = profit_MM, fill = Climate), stat = 'identity', position = position_dodge2(preserve = "single")) +
  geom_text(aes(x = sim, y = profit_MM, label=round(profit_MM,2)), vjust = -1, size=5, position = position_dodge(width = 1))+
  geom_point(aes(x = sim, y = precip_cm/25), size = 2, shape = 15, position = position_dodge(width = 1)) +
  scale_y_continuous(sec.axis = sec_axis(~.*25, name = 'Precipitation (cm)'), limits = c(0,4))+
  scale_x_discrete(labels=c( "Known Climate \n Unknown Weather", "Stochastic"))+
  theme_minimal()+
  theme(plot.title = element_text(size = 14, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust =0.5),
        axis.text.y.left = element_blank(),
        axis.title.y.left = element_blank(),
        #legend.key.width = unit(0.12, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'DML: Profit & Precipitation', y = 'Profit ($ MM)', x = '', size = 8, fill = 'Weather')+
  scale_fill_brewer(palette = "Dark2")+
  guides(fill = guide_legend(override.aes = list(shape = NA))) -> profitplot


profitplot
```


### Crop Yield

```{r}
scenario_avg %>% filter(sim != 'Stochastic_avg') %>% filter(sim != 'Expected Value') %>%
  ggplot(aes(x = sim, y = crop_yield_tonne, fill = Climate)) + 
  geom_bar(aes(x = sim, y = crop_yield_tonne, fill = Climate), stat = 'identity', position = position_dodge2(preserve = "single")) +
  geom_text(aes(x = sim, y = crop_yield_tonne, label=round(crop_yield_tonne,0)), vjust = -1, size=5, position = position_dodge(width = 1))+
  geom_point(aes(y = water_cm*8, x = sim), size = 2, shape = 17, position = position_dodge(width = 1)) +
  scale_y_continuous(sec.axis = sec_axis(~./8, name = 'Water Depth (cm)'), limits = c(0,800))+
  scale_x_discrete(labels=c( "Known Climate \n Unknown Weather", "Stochastic"))+
  theme_minimal()+
  theme(plot.title = element_text(size = 14, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust =0.5),
        axis.text.y.left = element_blank(),
        axis.title.y.left = element_blank(),
        #legend.key.width = unit(0.12, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'DML: Wheat Yield & Water Depth', y = 'Wheat Yield (tonnes)', x = '', size = 8, fill = 'Weather')+
  scale_fill_brewer(palette = "Dark2")+
  guides(fill = guide_legend(override.aes = list(shape = NA))) -> cyplot

cyplot

```


#### Investments

```{r}
waterinvestplot <- scenario_avg %>% filter(sim != 'Stochastic') %>% 
  ggplot(aes(x = sim, y = alt_water_cap_cm, fill = Climate)) + 
  geom_bar(aes(x = sim, y = alt_water_cap_cm, fill = Climate), stat = 'identity', position = position_dodge2(preserve = "single")) +
  geom_text(aes(x = sim, y = alt_water_cap_cm, label=round(alt_water_cap_cm,1)), vjust = -1, size=4, position = position_dodge(width = 1))+
  #geom_point(aes(y = water_cm/5, x = sim), size = 2, shape = 17, position = position_dodge(width = 1)) +
  #scale_y_continuous(sec.axis = sec_axis(~.*5, name = 'Water DDMLth (cm)'), limits = c(0,20))+
  scale_y_continuous(limits = c(0,20))+
  scale_x_discrete(labels=c( "Known Climate \n Unknown Weather", "Stochastic", "Expected \n Value"))+
  theme_minimal()+
  theme(plot.title = element_text(size = 14, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust =0.5),
        #legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'DML: Water Investments', y = 'Reverse Osmosis Capacity (cm)', x = '', size = 8)+
  scale_fill_brewer(palette = "Dark2")+
  scale_fill_manual(values = c("DC" = "#1b9e77", "DMC" = "#d95f02", "MC" = "#7570b3", "WC" = "#e7298a", 'Stoch' = 'blue', "EV" = "purple"))+
  #https://colorbrewer2.org/#type=qualitative&scheme=Dark2&n=6
  guides(fill = guide_legend(override.aes = list(shape = NA)))

elcinvestplot <- scenario_avg %>% filter(sim != 'Stochastic') %>% 
    ggplot(aes(x = sim, y = alt_elc_cap_kW, fill = Climate)) + 
  geom_bar(aes(x = sim, y = alt_elc_cap_kW, fill = Climate), stat = 'identity', position = position_dodge2(preserve = "single")) +
  geom_text(aes(x = sim, y = alt_elc_cap_kW, label=round(alt_elc_cap_kW,0)), vjust = -1, size=5, position = position_dodge(width = 1))+
  #geom_point(aes(y = elc_prod_MWh/2, x = sim), size = 2, shape = 19, position = position_dodge(width = 1)) +
  #scale_y_continuous(sec.axis = sec_axis(~.*2, name = 'Electricity Produced (MWh)'), limits = c(0,400))+
  scale_y_continuous(limits = c(0,350))+
  scale_x_discrete(labels=c( "Known Climate \n Unknown Weather", "Stochastic", "Expected \n Value"))+
  theme_minimal()+
  theme(plot.title = element_text(size = 14, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust =0.5),
        #legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'DML: Electricity Investments', y = 'Solar PV Capacity (kW)', x = '', size = 8)+
  scale_fill_brewer(palette = "Dark2")+
  scale_fill_manual(values = c("DC" = "#1b9e77", "DMC" = "#d95f02", "MC" = "#7570b3", "WC" = "#e7298a", 'Stoch' = 'blue', "EV" = "purple"))
  #http://sape.inf.usi.ch/quick-reference/ggplot2/colour



investplot <- grid.arrange(waterinvestplot, elcinvestplot, ncol = 2)

investplot

```


```{r}


# %like% from data.table library

stochvclimate1 <- stochvclimate1_df %>% mutate(climate = 'DC') %>% filter(scenario != 'Stage 1') %>% mutate(sim = ifelse(scenario == 'Dry_Climate', 'Known Climate Unknown Weather', 'Stochastic'))

stochvclimate2 <- stochvclimate2_df %>% mutate(climate = 'DMC') %>% filter(scenario != 'Stage 1') %>% mutate(sim = ifelse(scenario == 'Dry_Climate', 'Known Climate Unknown Weather', 'Stochastic'))

stochvclimate3 <- stochvclimate3_df %>% mutate(climate = 'MC') %>% filter(scenario != 'Stage 1') %>% mutate(sim = ifelse(scenario == 'Dry_Climate', 'Known Climate Unknown Weather', 'Stochastic'))

stochvclimate4 <- stochvclimate4_df %>% mutate(climate = 'WC') %>% filter(scenario != 'Stage 1') %>% mutate(sim = ifelse(scenario == 'Dry_Climate', 'Known Climate Unknown Weather', 'Stochastic'))

stochvclimate <- rbind(stochvclimate1, stochvclimate2, stochvclimate3, stochvclimate4) %>% mutate(groundwater = irrigation_water)
    

stochvclimate



```



```{r}

sim.labs <- c('KCUW', 'Stochastic')
names(sim.labs) <- c('Known Climate Unknown Weather', 'Stochastic')


stochvclimate %>% pivot_longer(c(alt_water,groundwater,total_water,precip), names_to = 'Water_Source', values_to = 'Water_DDMLth') %>%
  filter(Water_Source != 'total_water') %>%
  ggplot(aes(x = Year, y = Water_DDMLth, group = Water_Source, fill = Water_Source, color = Water_Source))+
  geom_area(position = position_stack(reverse = TRUE))+
  scale_y_continuous(breaks = seq(from = 0, to = 100, by = 25), limits =c(0,100))+
  scale_x_continuous(breaks = seq(from = 1, to = 25, by = 2))+
  #theme_minimal()+
  theme(plot.title = element_text(size = 14, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        #legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'DML: Water Production', y = 'Water Depth (cm)', x = 'Year', size = 8)+
  facet_grid( climate ~ sim, labeller = labeller(sim = sim.labs)) -> waterop


waterop
```


```{r}
stochvclimate %>% pivot_longer(c(alt_elc,utility_elc,total_elc), names_to = 'ELC_Source', values_to = 'ELC_DDMLth') %>%
  filter(ELC_Source != 'total_elc') %>%
  ggplot(aes(x = Year, y = ELC_DDMLth/1000, group = ELC_Source, fill = ELC_Source, color = ELC_Source))+
  geom_area(position = position_stack(reverse = TRUE))+
  scale_y_continuous(breaks = seq(from = 0, to = 750, by = 250), limits =c(0,750))+
  scale_x_continuous(breaks = seq(from = 1, to = 25, by = 2))+
  #theme_minimal()+
  theme(plot.title = element_text(size = 14, face = 'bold'), 
        legend.position = 'bottom', 
        legend.text = element_text(size = 12), 
        legend.title = element_blank(), 
        axis.title = element_text(size = 12), 
        axis.text = element_text(size = 10), 
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust =0.5),
        #legend.key.width = unit(0.06, 'in'), 
        legend.key.height = unit(0.06,'in'), 
        legend.margin = margin(t = 0, unit = 'cm'), 
        plot.margin = unit(x = c(0.5,0.5,0.5,0.5), units = 'mm') ) +
  labs(title = 'DML: Electricity Production', y = 'Electricity Produced (MWh)', x = 'Year', size = 8)+
  facet_grid( climate ~ sim, labeller = labeller(sim = sim.labs)) -> elcop


elcop
```

# All Dataframes

```{r}

scenario_avg
scenario_yearly_avg
sim_stats
stochvclimate
parameters
```

```{r}
solnplot_dml <- solnplot

profitplot_dml <- profitplot

cyplot_dml <- cyplot

investplot_dml <- investplot

waterinvestplot_dml <- waterinvestplot

elcinvestplot_dml <- elcinvestplot


waterop_dml <- waterop

elcop_dml <- elcop
```

```{r}
sim_stats_trad_dml <- sim_stats_trad
sim_stats_trad_dml
value_of_solns_DML
```

```{r}
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/MI-DML_profit.pdf", profitplot)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/MI-DML_cy.pdf", cyplot)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/MI-DML_invest.pdf", investplot)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/MI-DML_water.pdf", waterop)
ggsave(filename = "~/Coding/R/Research/Farm Model/Graphs/MI-DML_elc.pdf", elcop)
```