"""Stage 9: regenerate the figures from cleaned output.

    python scripts/make_figures.py

Archetype P is explicit that figures are **regenerated by a script, never by
running a notebook**, and that they **read cleaned output, never raw**. This
script reads only `results/clean/`, which `fews_stochopt.analysis` writes; it
never touches the 135 MB of per-run solver detail, because a figure that
re-derives per-year means is re-implementing that module and the second copy is
the one that drifts.

It replaces `stage2-r/farm_report.Rmd`, which drew the same figures in ggplot and
is archived verbatim under `archive/stage2-r/`.

Every figure carries a text alternative describing what it *shows*, written in
the same place as the plot. That is a one-sentence cost here and a project in
retrospect, and `figures/generated/README.md` collects them so a reader who
cannot see a plot is not asked to take it on trust.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import matplotlib  # noqa: E402

matplotlib.use("Agg")  # no display; this runs headless and in CI
import matplotlib.pyplot as plt  # noqa: E402
import pandas as pd  # noqa: E402

from fews_stochopt.analysis import clean_dir  # noqa: E402
from fews_stochopt.config import load_config, repo_root  # noqa: E402

ROOT = repo_root()
OUT = ROOT / "figures" / "generated"

# Colour is never the only carrier of meaning: every series also differs by
# marker or line style, and the palette avoids red/green and green/brown.
STYLE = {
    "Perfect Information": dict(color="#1b4965", marker="o", linestyle="-"),
    "Known Climate, Unknown Weather": dict(color="#5fa8d3", marker="s", linestyle="--"),
    "Stochastic": dict(color="#cae9ff", marker="^", linestyle="-."),
    "Expected Value": dict(color="#62506b", marker="D", linestyle=":"),
}

ALT: dict[str, str] = {}


def read(name: str) -> pd.DataFrame:
    path = clean_dir() / name
    if not path.exists():
        raise FileNotFoundError(
            f"{path} is missing. Cleaned output is written by "
            f"`python scripts/run_all.py`; figures never read the raw solver output."
        )
    frame = pd.read_csv(path)
    if frame.empty:
        raise ValueError(f"{path} parsed to zero rows")
    return frame


def save(fig, name: str, alt: str) -> Path:
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / name
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    ALT[name] = alt
    return path


def figure_profit_by_scenario(log) -> None:
    stats = read("scenario_stats.csv")
    wide = stats.pivot_table(
        index=["site", "label", "scenario"], columns="variable", values="value"
    ).reset_index()

    fig, axes = plt.subplots(1, 2, figsize=(11, 4), sharex=False)
    for ax, (site, group) in zip(axes, wide.groupby("site", sort=False)):
        group = group.set_index("scenario").loc[list(STYLE)].reset_index()
        y = range(len(group))
        ax.errorbar(
            group["profit_mean"], y, xerr=group["profit_h"], fmt="none",
            ecolor="#444444", capsize=4, linewidth=1,
        )
        for i, row in group.iterrows():
            ax.plot(row["profit_mean"], i, **STYLE[row["scenario"]],
                    markersize=8, markeredgecolor="#222222")
        ax.set_yticks(list(y))
        ax.set_yticklabels(group["scenario"], fontsize=8)
        ax.invert_yaxis()
        ax.set_title(group["label"].iloc[0], fontsize=10)
        ax.set_xlabel("Mean profit ($)")
        ax.ticklabel_format(axis="x", style="plain")
        ax.tick_params(axis="x", labelsize=8)
        ax.grid(axis="x", alpha=0.3)
    fig.suptitle("Mean profit by scenario, with 95% intervals", fontsize=12)
    save(fig, "profit_by_scenario.png",
         "Four horizontal 95% confidence intervals for mean profit, one per "
         "scenario, for each site. Perfect Information is highest at about "
         "$2.36M for Equally Probable and $1.98M for Dry Most Likely; Known "
         "Climate sits just below; Stochastic and Expected Value are lower and "
         "lie almost on top of each other. The intervals are far narrower than "
         "the gaps between the first three, and the gap between the last two is "
         "invisible at this scale - which is the point the value of the "
         "stochastic solution makes numerically.")
    log("  profit_by_scenario.png")


def figure_value_of_information(log) -> None:
    values = read("value_of_information.csv")
    order = ["Value_of_Known_Weather", "Value_of_Known_Climate",
             "Value_of_Perfect_Information", "Value_of_Stochastic_Solution"]
    short = {"Value_of_Known_Weather": "EVKW", "Value_of_Known_Climate": "EVKC",
             "Value_of_Perfect_Information": "EVPI",
             "Value_of_Stochastic_Solution": "VSS"}

    fig, axes = plt.subplots(1, 2, figsize=(11, 4))
    for ax, (site, group) in zip(axes, values.groupby("site", sort=False)):
        group = group.set_index("variable").loc[order].reset_index()
        x = range(len(group))
        ax.bar([i - 0.2 for i in x], group["published"], width=0.4,
               color="#cae9ff", edgecolor="#1b4965", hatch="//", label="published")
        ax.bar([i + 0.2 for i in x], group["value"], width=0.4,
               color="#1b4965", edgecolor="#1b4965", label="reproduced")
        ax.set_yscale("symlog", linthresh=1)
        ax.set_xticks(list(x))
        ax.set_xticklabels([short[v] for v in group["variable"]])
        ax.set_title(group["label"].iloc[0], fontsize=10)
        ax.set_ylabel("$ (symlog)")
        ax.grid(axis="y", alpha=0.3)
        ax.legend(fontsize=8)
    fig.suptitle("Value of information: published against reproduced", fontsize=12)
    save(fig, "value_of_information.png",
         "Paired bars comparing the paper's four value-of-information figures "
         "with the reproduced ones, on a symmetric log scale because the "
         "quantities span $0.34 to $108,725. The pairs are visually identical "
         "for EVKW, EVKC and EVPI at both sites. The only visible difference is "
         "VSS at Dry Most Likely, where the reproduced bar is slightly taller "
         "($964.89 against $940.90); at Equally Probable VSS is under a dollar "
         "and both bars are negligible. The numbers are in "
         "results/clean/value_of_information.csv.")
    log("  value_of_information.png")


def figure_yearly(log) -> None:
    yearly = read("yearly.csv")
    quantities = [("water", "Water applied (cm)"),
                  ("crop_yield", "Crop yield (tonne/ha)"),
                  ("alt_water", "Alternative water (cm)")]

    fig, axes = plt.subplots(len(quantities), 2, figsize=(11, 9), sharex=True)
    for row, (variable, ylabel) in enumerate(quantities):
        for col, site in enumerate(["EP", "DML"]):
            ax = axes[row][col]
            subset = yearly[(yearly["variable"] == variable) & (yearly["site"] == site)]
            for scenario, group in subset.groupby("scenario", sort=False):
                ax.plot(group["year"], group["value"], label=scenario,
                        markersize=3, linewidth=1.2, **STYLE[scenario])
            ax.set_ylabel(ylabel, fontsize=8)
            ax.grid(alpha=0.3)
            ax.tick_params(labelsize=8)
            if row == 0:
                ax.set_title(subset["label"].iloc[0], fontsize=10)
            if row == len(quantities) - 1:
                ax.set_xlabel("Year")
    axes[0][0].legend(fontsize=7, loc="best")
    fig.suptitle("Yearly means by scenario", fontsize=12)
    save(fig, "yearly_by_scenario.png",
         "A three-by-two grid of line charts: water applied, crop yield and "
         "alternative water, over 25 years, for each site and each of the four "
         "scenarios. Every series is close to flat across years, because each "
         "year's weather is an independent draw and the investment is fixed at "
         "the start. Perfect Information applies the most water and gets the "
         "highest yield; Expected Value and Stochastic track each other closely. "
         "The numbers are in results/clean/yearly.csv.")
    log("  yearly_by_scenario.png")


def figure_climates(log) -> None:
    climates = read("climates.csv")
    fig, ax = plt.subplots(figsize=(7, 4.5))
    markers = {"EP": "o", "DML": "s"}
    for site, group in climates.groupby("site", sort=False):
        ax.plot(group["mean_precip_cm"], group["mean_profit_perfect_information"],
                marker=markers[site], linestyle="--", linewidth=1,
                label=group["label"].iloc[0],
                color="#1b4965" if site == "EP" else "#62506b")
        for _, r in group.iterrows():
            ax.annotate(f"climate {r['climate']:.0f}",
                        (r["mean_precip_cm"], r["mean_profit_perfect_information"]),
                        textcoords="offset points", xytext=(6, -10), fontsize=7)
    cfg = load_config()
    peak = -cfg.yield_coeffs.a1 / (2 * cfg.yield_coeffs.a2)
    ax.axvline(peak, color="#888888", linestyle=":", linewidth=1)
    ax.annotate(f"yield peaks at {peak:.0f} cm", (peak, ax.get_ylim()[0]),
                textcoords="offset points", xytext=(4, 14), fontsize=7, rotation=90)
    ax.set_xlabel("Mean growing-season precipitation (cm)")
    ax.set_ylabel("Mean profit under perfect information ($)")
    ax.set_title("More rain is not always better", fontsize=11)
    ax.grid(alpha=0.3)
    ax.legend(fontsize=8)
    save(fig, "profit_against_rainfall.png",
         "Mean profit under perfect information against mean precipitation, for "
         "the four climates at each site, with a vertical line at the 72 cm "
         "where the yield curve peaks. The relationship is NOT monotone: "
         "climate 3 averages about 55 cm and earns less than climate 2 at about "
         "50 cm, because climate 3 is uniform across all five weather states and "
         "puts a fifth of its years past the yield peak, where extra water "
         "reduces yield and the farm cannot shed it. The two sites lie almost on "
         "top of each other, which is the evidence that they sample the same "
         "four climates.")
    log("  profit_against_rainfall.png")


def figure_precipitation(log) -> None:
    precip = read("precipitation_states.csv")
    if precip["regenerated_share"].isna().all():
        log("  precipitation_states.png  SKIPPED - no regenerated sample")
        return
    fig, axes = plt.subplots(1, 2, figsize=(11, 4))
    for ax, (site, group) in zip(axes, precip.groupby("site", sort=False)):
        x = range(len(group))
        ax.bar([i - 0.2 for i in x], group["committed_share"], width=0.4,
               color="#1b4965", label="committed input")
        ax.bar([i + 0.2 for i in x], group["regenerated_share"], width=0.4,
               color="#cae9ff", edgecolor="#1b4965", hatch="\\\\",
               label="regenerated")
        ax.set_xticks(list(x))
        ax.set_xticklabels([f"{v:.2f}" for v in group["precip_cm"]], fontsize=8)
        ax.set_xlabel("Precipitation (cm)")
        ax.set_ylabel("Share of run-years")
        ax.set_title(group["label"].iloc[0], fontsize=10)
        ax.grid(axis="y", alpha=0.3)
        ax.legend(fontsize=8)
    fig.suptitle("Weather states: committed input against a fresh draw", fontsize=12)
    save(fig, "precipitation_states.png",
         "Paired bars showing the share of run-years in each of the five weather "
         "states, for the committed input and for a fresh sample drawn from the "
         "reconstructed transition matrix. The pairs are indistinguishable at "
         "every state and both sites; the largest difference is under 0.002, "
         "well inside sampling error. This is the check that the reconstructed "
         "matrix is right, since the original's exact draws cannot be recovered.")
    log("  precipitation_states.png")


def write_alt_text() -> Path:
    path = OUT / "README.md"
    lines = [
        "# Generated figures",
        "",
        "Regenerated by `python scripts/make_figures.py`, which reads only",
        "`results/clean/`. **Never edit these by hand** — they are build outputs.",
        "",
        "These are *this repository's* figures. The paper's own figures are in",
        "`../` and are a frozen record; the two are not the same artifact and",
        "should not be compared pixel for pixel.",
        "",
        "## Text alternatives",
        "",
        "Every figure has one, written in the same place as the plot rather than",
        "added afterwards. Each says what the figure *shows*, not what it is, and",
        "names the cleaned-output file holding the numbers behind it.",
        "",
    ]
    for name in sorted(ALT):
        lines += [f"### `{name}`", "", ALT[name], ""]
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--quiet", action="store_true")
    args = p.parse_args(argv)
    log = (lambda *a: None) if args.quiet else print

    log(f"reading cleaned output from {clean_dir()}")
    log(f"writing figures to {OUT}")
    figure_profit_by_scenario(log)
    figure_value_of_information(log)
    figure_yearly(log)
    figure_climates(log)
    figure_precipitation(log)
    readme = write_alt_text()
    log(f"  {readme.name}  ({len(ALT)} text alternatives)")

    if not ALT:
        print("no figures were produced", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
